### ISSUE TITLE
Flow Nodes Overview -> Blind Mode: Missing Details

### ISSUE THREAD

**Issue by AlexTeusz** [Cognigy/Documentation#1]
Hello Docs Team,

Could you please add more detailed information about the blind mode, especially which fields will be masked by default?

Link to docs: https://docs.cognigy.com/ai/flow-nodes/flow-nodes-overview/?h=mode#blind-mode

**Comment by EgleHelms** [comment]
Thanks, this is added to the backlog of documentation improvements.
