### ISSUE TITLE
[IMPROVEMENT] - Functions

### ISSUE THREAD

**Issue by mjrgreenslade** [Cognigy/Documentation#12]
**URL of the page that needs improving:** {{ https://github.com/Cognigy/Documentation/blob/main/docs/en/docs/ai/resources/build/functions.md }}

**Suggestion of how to improve the page**
- Request clearer explanation/statement of limitations and cost of functions. E.g. How many can be run at one time, should a customer be charged more to increase the limit etc
- Request suggestions of the pitfalls of using functions e.g. how they should not be applied in practical examples and what their intention of use is.

**Comment by mjrgreenslade** [comment]
Further suggestion: 

- Document should clearly outline the appropriate way to test a function in a flow as the inject and notify api cannot be used to test in the interaction panel (this should be highlighted)
- Document should describe the trigger function flow node and what the reason each of the case nodes are there for and what their functionality is.

**Comment by EgleHelms** [comment]
Thanks for submitting this. This is now in our backlog and will be improved.
