### ISSUE TITLE
[Feedback] User Input Timeout Config - /ai/flow-nodes/generic-voice-nodes/user-input-timeout-config/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#17]
Headline of this page https://docs.cognigy.com/ai/flow-nodes/generic-voice-nodes/user-input-timeout-config/ says "Transfer", while it should be "User Input Timeout Config".

**Comment by CognigyTechWriter** [comment]
> Headline of this page https://docs.cognigy.com/ai/flow-nodes/generic-voice-nodes/user-input-timeout-config/ says "Transfer", while it should be "User Input Timeout Config".

Thank you for your feedback! We have updated the page https://docs.cognigy.com/ai/flow-nodes/generic-voice-nodes/user-input-timeout-config/
