### ISSUE TITLE
[Feedback] Lookup - /ai/flow-nodes/logic/lookup/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#19]
Hi, 

Documentation describes 5 Lookup Types:
- Intent
- State
- Type
- Mode
- Cognigy Script

Missing are:
- Text
- Handover status
Currently I had to test to figure out exact behavior of Text type.
Thanks for consideration!

**Comment by CognigyTechWriter** [comment]
Thanks for submitting this. This is now in our backlog and will be improved.

**Comment by MaciejLitwiniec** [comment]
Great!
By saying "Currently I had to test to figure out exact behavior of Text type" I meant it was not clear if type Text is case sensitive or not. - It is.

**Comment by CognigyTechWriter** [comment]
Dear Maciej,

We have added these missing Lookup types and a note about case sensitivity to our documentation.

Thank you again for informing us, this issue will not be closed.
