### ISSUE TITLE
[Feedback] Deploy a Webchat Endpoint - /ai/endpoints/webchat/deploy-webchat-endpoint/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#21]
Hi, 
In 4.52 there is an improvement: 
"Added the settings for both maintenance and out-of-business-hours modes to the Webchat Endpoint"
https://docs.cognigy.com//release-notes/4.52/#improvements
<img width="600" alt="image" src="https://github.com/Cognigy/Documentation/assets/11756474/be326d29-9119-4c4c-9244-2df53e16f3f7">

Those two new settings are not described in related documentation.
-https://docs.cognigy.com/ai/endpoints/webchat/deploy-webchat-endpoint/
-https://docs.cognigy.com/ai/endpoints/webchat/webchat-features/
-https://docs.cognigy.com/ai/endpoints/webchat/webchat/

Although tooltips are straight forward I by chance found this in Endpoint configuration and related to latest release notes.
If I would go from documentation first I would not learn about this options.

Thanks!

**Comment by CognigyTechWriter** [comment]
Hello,

The Webchat configuration documentation is primarily located on GitHub. We have included the necessary references. More details are in the release notes [here](https://docs.cognigy.com/release-notes/4.52/#improvements).

Thank you for your feedback!

**Comment by MaciejLitwiniec** [comment]
Ok. Thanks!

**Comment by MaciejLitwiniec** [comment]
Ok. Thanks!
