### ISSUE TITLE
[Feedback] Question - /ai/flow-nodes/message/question/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#22]
Documentation says following:
„Question Nodes have a Type which defined what kind of answer is required from the user before the conversation continues. After a question was asked and the user provided an answer, the answer is validated according to its Type. If it passes, the answer is considered valid, is stored and the conversation continues.”

However, this can be skipped/omitted if there is an Attached Flow and intent in user's input is found. 
We like the way it works, but learned about this only through testing.

Consider a reference to Attached Flow documentations where we can find.
„If the Intent of the attached Flow is scored highest, the attached Flow is executed instead of the main Flow.”
https://docs.cognigy.com/ai/nlu/attachments/attached-flows/  

Thanks.

**Comment by CognigyTechWriter** [comment]
Thanks for submitting this. This is now in our backlog and will be improved.

**Comment by CognigyTechWriter** [comment]
We have added a new Attached Flows note and link in our documentation: [Question](https://docs.cognigy.com/ai/flow-nodes/message/question/).

Thanks again for reporting this, we will close this issue at this time.
