### ISSUE TITLE
[Feedback] HTTP Request - /ai/flow-nodes/services/http-request/

### ISSUE THREAD

**Issue by SgastonBW** [Cognigy/Documentation#23]
Can you provide what the syntax would be to use variables from the context store in the HTTP request JSON payload option? Standard JS methods don't seem to work here including string interpolation. It always says invalid JSON and sends a blank request.

**Comment by CognigyTechWriter** [comment]
Thanks for submitting this. This is now in our backlog and will be improved.

**Comment by CognigyTechWriter** [comment]
Please refer to [CognigyScript](https://docs.cognigy.com/ai/tools/cognigy-script/#for-json-arguments) for an example payload.

```
{
    "customer_orders": {
        "$cs": {
            "script": "context.orders",
            "type": "object"
        }
    }
}
```
We have also added a new link to this here in [HTTP Request](https://docs.cognigy.com/ai/flow-nodes/services/http-request/#payload).

Thanks again for reporting this, we will close this issue at this time.
