### ISSUE TITLE
[IMPROVEMENT] - ServiceNow Live Chat integration - unclear Transformer installation

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#25]
**URL for the page that needs improving:** 
https://support.cognigy.com/hc/en-us/articles/4407410019602-Service-Now-Connect-to-Live-Chat#h_01FGVG4EJTBYDHNG1AF4J9FMQG

In "Installation" section it is said:
"Note the enabled transformer functions. Please download the latest Endpoint Transformer code from the attachments of this Help Center article! There is one for socket- and one for webhook-based endpoints."

However, picture shown above represent Endpoint Editor for Webchat type of endpoint. 
This is confusing as later documentation does not clarify what will be the difference of using Socket or Webhooks with SNOW and if I should actually apply either of given scripts in Webchat endpoint.

![image](https://github.com/Cognigy/Documentation/assets/11756474/5838870b-4557-44d8-a0bb-e076063b11aa)

Thanks for clarifying that.

**Comment by CognigyTechWriter** [comment]
Thanks for submitting this issue with the Help Center article for Service Now. 

This is now in our backlog and will be improved, we will update you once this has been completed.

**Comment by CognigyTechWriter** [comment]
Dear Maciej,

We have added additional clarification on which Transformer Code to use in the linked document.

Thanks for raising this issue with us. This request will now be closed.
