### ISSUE TITLE
[IMPORVEMENT] - CTXT format description

### ISSUE THREAD

**Issue by RobG-LHind** [Cognigy/Documentation#26]
**URL for the page that needs improving:**
https://docs.cognigy.com/ai/knowledge-ai/?h=ctxt#explore-a-knowledge-ai-project 

**Suggestion of how to improve the page**
As CTXT is the preferred format to controll chunk-splitting, it would be very helpful to get as much information about it as possible - it seems to be markup-format with some additions. 
Please describe the CTXT format in detail (esp the non-standard-markdown ones).
Please give a list of allowed meta-entries. 
Which of them are mandatory?
Which of them have to be repeated in each chunk, to be part of the answer (general pictures, links)?

Thanks

**Comment by RobG-LHind** [comment]
https://docs.cognigy.com/ai/knowledge-ai/ctxt/

thx

**Comment by CognigyTechWriter** [comment]
Hello dear RobG-LHind,

Thanks for submitting this. Yes, we recently release [this article](https://docs.cognigy.com/ai/knowledge-ai/ctxt/). Is the article covering your questions? Please let us know if you have any remaining questions.
