### ISSUE TITLE
[Feedback] Services - /ai/flow-nodes/services/services/

### ISSUE THREAD

**Issue by jfinke-WAGO** [Cognigy/Documentation#27]
![image](https://github.com/Cognigy/Documentation/assets/101115459/a1d0bceb-5101-433f-abea-be362903b7fe)

Documentation for some nodes is missing, e.g. "Check Agent Availability". Please add.

**Comment by CognigyTechWriter** [comment]
Hello

Thank you for submitting this. This task is in process and the content will be released soon.

**Comment by CognigyTechWriter** [comment]
Hello 

The [Check Agent Availability ](https://docs.cognigy.com/ai/flow-nodes/services/check-agent-availability/) article has been released. 

This issue will now be marked as closed. Please let us know should you have any additional issues to raise.
