### ISSUE TITLE
[Feedback] Build your First xApp - /ai/xApp/build/first-xApp/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#28]
Hi, 

This refers to https://docs.cognigy.com/ai/xApp/build/first-xApp/#configure-a-basic-xapp-flow

In documentation we can find following code.
![image](https://github.com/Cognigy/Documentation/assets/11756474/32970d8c-8a6b-4d0b-a4b0-c84a9ba28db9)

It should be:
`input.data._cognigy._app.payload.status  == 'new'`

**Comment by CognigyTechWriter** [comment]
Hello MaciejLitwiniec,

We have made improvements to this [article](https://docs.cognigy.com/ai/xApp/build/first-xApp/#configure-a-basic-xapp-flow). Thank you for your feedback!
