### ISSUE TITLE
[Feedback] Regex Slot Filler - /ai/flow-nodes/nlu/regex-slotfiller/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#29]
There seems to be a typo in given example.

> Example: * /^1\d{​​​​7}​​​​$/g. 

In regular expressions, the asterisk * is a quantifier that means "zero or more occurrences of the preceding element." However, in the regex pattern you've provided, the asterisk appears to be placed outside of the regular expression itself and not in the context of its usual function within a pattern.

**Comment by CognigyTechWriter** [comment]
Hello MaciejLitwiniec,

We have made improvements to this [article](https://docs.cognigy.com/ai/flow-nodes/nlu/regex-slotfiller/). Thank you for your feedback!

**Comment by MaciejLitwiniec** [comment]
I would also remove dot from end of example. It is not value adding while it can introduce an error.

**Comment by CognigyTechWriter** [comment]
Thank you. We fixed the page.
