### ISSUE TITLE
[Feedback] Cognigy NLU: V1 to V2 - /ai/installation/migration/from-nlu-v1-to-v2-migration/

### ISSUE THREAD

**Issue by sturgesas** [Cognigy/Documentation#30]
Misleading information "To remove NLP V2 " Should be NLP V1
-----------------
Remove the NLP V1 Stack[¶](https://docs.cognigy.com/ai/installation/migration/from-nlu-v1-to-v2-migration/#remove-the-nlp-v1-stack)
To remove the NLP # V2 stack, remove the service-nlp-score-<lang> and service-nlp-train-<lang> services from your values-local.yaml file.
-----------------

**Comment by CognigyTechWriter** [comment]
The [article](https://docs.cognigy.com/ai/installation/migration/from-nlu-v1-to-v2-migration/#check-if-migration-is-complete) has been fixed. Thank you for your feedback!
