### ISSUE TITLE
[Feedback] HTTP Request - /ai/flow-nodes/services/http-request/

### ISSUE THREAD

**Issue by kedoska** [Cognigy/Documentation#31]
Hello team,

Is there any default timeout for the HTTP Request Node?

**Comment by CognigyTechWriter** [comment]
Hello,

Thank you for submitting this.

We have updated the [Node page](https://docs.cognigy.com/ai/flow-nodes/services/http-request/#description). The current limit is 8 seconds for a shared Cognigy installation.
