### ISSUE TITLE
Fix version number display in the re-release version.

### ISSUE THREAD

**Issue by sturgesas** [Cognigy/Documentation#32]
https://docs.cognigy.com//release-notes/4.68/ On this tag the version is displayed as 4.67
![Screenshot 2024-01-23 150849](https://github.com/Cognigy/Documentation/assets/108128188/020ea25f-0f2d-4c48-9967-6a9cddd075af)

**Comment by CognigyTechWriter** [comment]
Hello,

The issue has been fixed. Thanks for your feedback!
