### ISSUE TITLE
[Feedback] Context - /ai/tools/interaction-panel/context/

### ISSUE THREAD

**Issue by antonxt** [Cognigy/Documentation#33]
Not clear when Default Context is actually applied. I think, it is when the Endpoint starts with the flow with the Default Context? I tried starting in another flow, then Go To the flow with a Default Context, but the context did not apply

**Comment by CognigyTechWriter** [comment]
Thanks for submitting this. This is now in our backlog and will be improved.

**Comment by CognigyTechWriter** [comment]
Hello,

We have explained the Default Context concept within the [Flow](https://docs.cognigy.com/ai/resources/build/flows/#default-context)  article. If you have any further questions, please let us know.
