### ISSUE TITLE
[Feedback] Code - /ai/flow-nodes/code/code/ - "Text Cleaner" link set incorrectly

### ISSUE THREAD

**Issue by peternann** [Cognigy/Documentation#34]
The Code node page mentions a "Text Cleaner" via "getTextCleaner" (linked to https://docs.cognigy.com/ai/flow-nodes/code/actions/#text-cleaner), but the linked page make no further mention of what this is.

Actually, just the hyperlink is wrong. The correct link seems to be this:
https://docs.cognigy.com/ai/tools/text-cleaner/

**Comment by CognigyTechWriter** [comment]
Hello,

Thank you for your feedback. We have fixed [this page](https://docs.cognigy.com/ai/flow-nodes/code/code/) and provided the relevant link.
