### ISSUE TITLE
[Feedback] Endpoint Configuration - /webchat/v3/configuration/

### ISSUE THREAD

**Issue by MaciejLitwiniec** [Cognigy/Documentation#36]
Hi,

Section for Previous Conversations does not clarify where the past conversation is stored.
As this is user data we need to have this clear in order to be compliant to local regulations, and business requirements.

Thanks for clarification.

link: https://docs.cognigy.com/webchat/v3/configuration/#previous-conversations

BR,
Maciej

**Comment by CognigyTechWriter** [comment]
Hello Maciej,

We have updated the [Previous Conversations](https://docs.cognigy.com/webchat/v3/configuration/#previous-conversations) section. Thank you for your feedback!
